#!/bin/bash

HOME=/home/jonathan
cd ~/rawdisk2

function notify(){
  r=$?; [ ! -z "$2" ] && r=$2
  [ $r = 0 ] \
  && notify-send -h string:bgcolor:#84b826 "$1 terminate" \
  || notify-send -h string:bgcolor:#bb3456 "$1 error"
}

echo "$1"

case "$1" in
  https://1fichier.com/*)
    nf=.1fichier
    while [ 1 ]; do
      wget --header='Cookie: AF=2549450' -O $nf "$1"
      f=$(awk 'BEGIN{e=0} /attendre encore/{gsub(/^.*>/, ""); print; e=142} /Nom du fichier/{getline; gsub(/^[^>]+>|<\/td>.*$/, ""); print $0; exit e}' $nf)
      r=$?
      echo "$f"
      [ $r -ne 142 ] && break
      date
      f=${f:27}
      f=${f/ *}
      sleep "${f}m"
      sleep 1m
    done
    if [ $r -ne 0 ] || [ -z "$f" ] ; then
      sleep 2;
      exit $r
    fi
    u=$(wget --header='Cookie: AF=2549450' --post-data 'submit=Acceder%20au%20téléchargement&adzone='"$(awk '/adzone/{ gsub(/^.*value="|" \/>$/, ""); print $0 ; exit }' $nf)" -O- "$1" | \
        awk '/Cliquer ici pour télécharger le fichier/{ gsub(/[^<]+<a href="|" .*$/, ""); print $0 ; exit }')
    echo wget -c -O "'${f//\'/\'\\\'\'}' '$u'
$0 '${1//\'/\'\\\'\'}'" > ~/rawdisk/1fichier
    rm -- "$nf"
    r=1
    i=0
    while [ $r -ne 0 ] && [ $i -ne 5 ] ; do
      wget -c -O "${f//\//}" "$u"
      r=$?
      ((++i))
    done
    sleep 4
    notify "1fichier: $f" $r
    exit $r
    ;;

  https://uptobox.com/* | http://uptobox.com/*)
    d=
    cookie=.$$.cookie
    while [ 1 ]; do
      d=$(curl -b $cookie -c $cookie "$1" | awk '/waitingToken/{ gsub(/^.*value='\''|'\''.*/, ""); print ; exit }')
      [ ! -z "$d" ] && break
      echo empty token, wait 5 minutes
      sleep 5m
    done
    sleep 31
    f=$(curl -b $cookie -c $cookie -d waitingToken="$d" "$1" | awk '/big-button-green-flat mt-4 mb-4'\''>/{ gsub(/^<a href="|".*/, ""); print ; exit }')
    rm -- "$cookie"
    echo wget -c "'${f//\'/\'\\\'\'}'
$0 '${1//\'/\'\\\'\'}'" > ~/rawdisk/uptobox
    wget -c "$f"
    notify "uptobox: $(basename "${f//%20/ }")"
    ;;

  https://www.youtube.com/* | http://www.youtube.com/*)
    ~/.local/bin/youtube-dl --no-part -k --no-mtime --youtube-skip-dash-manifest --merge-output-format none --ffmpeg-location ~/rawdisk --no-playlist "$1"
    notify "youtube: $1"
    sleep 5
    ;;

  http://www.japscan.cc/* | https://www.japscan.cc/*)
    ~/game/dl-japscan "$1"
    notify "japscan: $1"
    ;;

  http://www.anime-ultime.net/info*)
    IFS=/ read _ _ _ _ id _ <<<"$1"
    s=$(curl http://www.anime-ultime.net/ddl/authorized_download.php --data "idfile=$id&type=orig")
    echo $s
    [ ${s:8:1} != t ] && echo wait 45s && sleep 46
    s=$(curl http://www.anime-ultime.net/ddl/authorized_download.php --data "idfile=$id&type=orig")
    echo $s
    s=$(sed -E 's/.*"link":"([^"]+)".*/\1/;s#\\/#/#g' <<<"$s")
    echo $s
    echo "$0 'http://www.anime-ultime.net/${s//\'/\'\\\'\'}'" > ~/rawdisk/anime-ultime
    wget -c -- "http://www.anime-ultime.net/$s"
    notify "anime-ultime: $1"
    ;;

  http://www.anime-ultime.net/file*)
    false
    notify "anime-ultime: $1"
    ;;

  *)
    echo "$1" > ~/rawdisk/dl
    plowdown "$1"
    notify "*: $1"
    ;;
esac
