#!/bin/zsh
gmic_args=''
for ((y=0;y<5;++y)) {
  for ((x=0;x<5;++x))
    gmic_args+=" --crop[0] {$x*int(w#0/5)},{$y*int(h#0/5)},{$(($x+1))*int(w#0/5)},{$(($y+1))*int(h#0/5)-1}"
}

for ((y=4;y>=0;--y)) {
  x=0 ; for i in 3 1 5 2 4 ; do
    gmic_args+=" -image[0] [-$(($i+$y*5))],{$x*int(w#0/5)},{$y*int(h#0/5)}"
    x+=1
  done
}

find "$@" -type f -exec gmic {} $=gmic_args -keep'[0]' -o {} \;
