#!/usr/bin/env zsh
files=()
for f in $@ ; {
  [[ $f[1] == / ]] && p= || p=./
  [ -d $f ] && files+=($p$f/**/*(^/)) || files+=($p$f)
}

for ((i=1; i <= $#files; i+=100)) {
  gmic $files[$i,$(($i+99))] \
  -adjust_colors'[0-100%]' -10,20\
  dk=0 \
  -repeat '$!,k' \
    -if '{w#$dk>h#$dk}' \
      -split_tiles'[$dk]' 2,1 \
      -name'[{$dk+1}]' '{$dk,f}/{$dk,b}_a.{$dk,x}' \
      dk+=1 \
    -fi \
    dk+=1 \
  -done \
  -autocrop'[0-100%]' \
  -repeat '$dk,k' \
    -if '{w#$k>900}' \
      -resize'[$k]' '{900},{h#$k/(w#$k/900.)}' \
    -fi \
    -o'[$k]' 'jpg:{$k,n},40' \
  -done -q
}
