#!/bin/zsh
files=()
for f in $@ ; {
  [[ $f[1] == / ]] && p= || p=./
  [[ -d $f ]] && files+=($p$f/**/*(^/)) || files+=($p$f)
}

intensity=${INTENSITY:-20}
adjust_colors=${ADJUST:-0,0,-$intensity,0,0,0}

for ((i=1; i <= $#files; i+=100)) {
  gmic $files[$i,$(($i+99))] -adjust_colors $adjust_colors -ow -q
}
