#!/bin/zsh
_script_run(){ ;gmic "$@" 'j={$!-1}' -repeat '$!,k' 'f={$j,n}' -split_tiles'[$j]' -100,1 -repeat '{($!-$j)/2-1},i' -move'[{$i*2+$j+1}]' '{$i*2+$j}' -done -append'[$j-{$!-1}]' x -split_tiles'[$j]' 1,-100 -repeat '{($!-$j)/2-1},i' -move'[{$i*2+$j+1}]' '{$i*2+$j}' -done -append'[$j-{$!-1}]' y -o'[$j]' '$f' -rm'[$j]' 'j-=1' -done }

files=()
for f in $@ ; {
  [[ $f[1] == / ]] && p= || p=./
  [ -d $f ] && files+=($p$f/**/*(^/)) || files+=($p$f)
}

for ((i=1; i <= $#files; i+=100)) {
  _script_run $files[$i,$(($i+99))]
}

