#!/bin/zsh
files=()
for f in $@ ; {
  [[ $f[1] == / ]] && p= || p=./
  [[ -d $f ]] && files+=($p$f/**/*(^/)) || files+=($p$f)
}

for ((i=1; i <= $#files; i+=100)) {
  gmic $files[$i,$(($i+99))] -adjust_colors 0,0,-20,0,0,0 -ow -q
}

