#!/bin/zsh

set -e

profile=${1:-default}
FIREFOX=~/.mozilla/firefox/

cd ~/rawdisk/ff/.mozilla/firefox
dl=(*.$profile(N))
if [ -z $dl ] || [ ! -d $dl ] ; then
  ar=($FIREFOX/*.$profile.7z(N))
  if [[ -z $ar ]] ; then
    dl=($FIREFOX/*.$profile)
    d=$dl[1]
    cp -R --preserve=all $d .
    d=$d:t
  else
    ar=$ar[1]
    cp $ar .
    ar=${ar:t}
    7zr x $ar
    d=${ar:0:-3}
  fi
else
  d=$dl[1]
fi

#{
#  sleep 30
#  mv ~/rawdisk2/STG-backups/* ~/STG-backups/
#  rmdir ~/rawdisk2/STG-backups
#}&

# f=list.$d.l
# ~/game/sync_tmp_dir -r $d $f &&
HOME=~/rawdisk/ff firefox -P $profile
# cp $f $f.old
# ~/game/sync_tmp_dir -u $d $f ~/.mozilla/firefox/ >&1 >~/rawdisk/rfirefox.sync.$$
[[ $(($RANDOM % 10)) == 1 ]] && for f in $d/**/*.sqlite ; do sqlite3 "$f" 'VACUUM;'; done ||:
mv $FIREFOX/$d.7z.old $FIREFOX/$d.7z.old.old ||:
mv $FIREFOX/$d.7z $FIREFOX/$d.7z.old ||:
7zr a $d.7z $d
cp $d.7z $FIREFOX/

7zr a ~/STG-backups/stg-backups.7z ~/rawdisk2/STG-backups/*
rm -r ~/rawdisk2/STG-backups
