#!/bin/zsh

set -e

profile=${1:-default}

cd ~/rawdisk/ff/.mozilla/firefox
dl=(*.$profile(N))
if [ -z $dl ] || [ ! -d $dl ] ; then
  zip=(~/.mozilla/firefox/*.$profile.zip(N))
  if [ -z $zip ] ; then
    dl=(~/.mozilla/firefox/*.$profile)
    d=$dl[1]
    cp -R --preserve=all $d .
    d=$d:t
  else
    zip=$zip[1]
    cp $zip .
    zip=${zip:t}
    unzip $zip
    d=${zip:0:-4}
  fi
else
  d=$dl[1]
fi

# f=list.$d.l
# ~/game/sync_tmp_dir -r $d $f &&
HOME=~/rawdisk/ff firefox -P $profile
# cp $f $f.old
# ~/game/sync_tmp_dir -u $d $f ~/.mozilla/firefox/ >&1 >~/rawdisk/rfirefox.sync.$$
for f in $d/**/*.sqlite ; do sqlite3 "$f" 'VACUUM;'; done
zip -1 -r $d.zip $d
cp $d.zip ~/.mozilla/firefox/
