#!/bin/bash
set -e
pid=$(xdotool getactivewindow getwindowpid %@)
s=${"$(</proc/$pid/stat)"/* (#b)([TS]) */${match[1]}}
read name < /proc/$pid/cmdline || :
case "$name" in
  ''|urxvt*) exit 0 ;;
  *) [ "$s" = 'T' ] && kill -CONT $pid || kill -STOP $pid
esac
