#!/bin/zsh
set -e
setopt extendedglob
pids=(${${(M)${(f)"$(ps aux)"}:#*\/firefox*}/[^0-9]#(#b)([0-9]#)*/$match[1]})
[ $#pids -eq 0 ] && exit 1
read x x s x < /proc/$pids[1]/stat
[ "$s" = 'T' ] && t=CONT || t=STOP
kill -$t $=pids
