#!/usr/bin/env zsh

emulate -L zsh -o extendedglob

local lines lines2 def
def=$(sdcv -n "$@") || return $?
lines=(${(f@)def})
lines2=(${(M)lines:#[0-9]*})
echo -E '> '${${lines[3]/#-->}:l}
if [[ -z $lines2 ]]; then
  lines2=(${(M)lines:#    *})
  echo -E "${lines2[1]:4}"
else
  local -i i=0
  for line in $lines2 ; do
    echo -E $'\033'"[$((i%2?33:35));1m$line"
    ((i++))
  done
fi
