#!/usr/bin/env zsh

emulate -L zsh -o extendedglob

local lines lines2 def
def=$(sdcv -n "$@") || exit $?
lines=(${(f@)def})
echo -E '> '${${lines[3]/#-->}:l}
local -i i j ie=$#lines
for ((i=1; i<=ie; i++)); do
  case $lines[i] in
    ' '*) echo -E $'\033[33;1m'$lines[i]$'\033[0m'
          echo -E "${(F)lines[i+1,-1]}"
          exit
          ;;
    '1'*) echo -E $'\033[33;1m'$lines[i]$'\033[0m'
          j=1
          for ((i++; i<=ie; i++)); do
            if [[ $lines[i] = [0-9]* ]]; then
              echo -E $'\033'"[$((j%2?33:35));1m$lines[i]"$'\033[0m'
              ((j++))
            else
              echo -E $lines[i]
            fi
          done
          exit
          ;;
  esac
  echo -E $lines[i]
done
