#!/usr/bin/env zsh
duration()
{
  zmodload zsh/datetime
  # evaluable command for alias/functions interpretation
  local cmd=(${(q)@})
  local -F t1=$EPOCHREALTIME
  eval $cmd
  local -F 3 t2=$EPOCHREALTIME
  ((t2-=t1))
  echo $t2 >&2
}
