#!/usr/bin/env zsh
gmic "$@" \
  -repeat '$!' \
    -if '{w#$>>h#$>}' \
      -split_tiles'[$>]' 2,1 \
      -o'[{$>+1}]' '{$>,f}/{$>,b}_a.{$>,x}' \
      -ow'[$>]' \
      -rm'[$>]' \
    -fi \
  -done -q
