#!/usr/bin/env zsh

eval "_script_run () {
  $(<$1)
}"
shift

files=()
for f in $@ ; {
  [[ $f[1] == / ]] && p= || p=./
  [ -d $f ] && files+=($p$f/**/*(^/)) || files+=($p$f)
}

for ((i=1; i <= $#files; i+=100)) {
  _script_run $files[$i,$(($i+99))]
}
