#!/bin/zsh

setopt extendedglob

device_id=${"$(xinput)"/(#b)*HID*Keyboard[[:blank:]]##id=([0-9]##)*/${match}}

if [ -z $match ]; then
  echo 'Unknown HID device' >&2
  exit 1
fi

XBK_DIR=$0:A:h
xkbcomp -I$XBK_DIR -i $device_id -synch - $DISPLAY <<<'xkb_keymap {
    xkb_keycodes  { include "evdev" };
    xkb_types     { include "complete" };
    xkb_compat    { include "complete" };
    xkb_symbols   { include "custom(ctrl)" };
};
'
# xkb_geometry  { include "pc(pc104)" };
