#!/bin/zsh

setopt extendedglob

device_id=${${(M)${(f)"$(xinput)"}:#* HID * Keyboard[[:blank:]]*}/(#b)*id=([0-9]##)*/${match}}

if [ -z $match ]; then
  echo 'Unknown HID device' >&2
  exit 1
fi

# /usr/share/X11/xkb/symbols/us

XBK_DIR=$0:A:h
xkbcomp -w0 -I$XBK_DIR -i $device_id -synch - $DISPLAY <<<'xkb_keymap {
    xkb_keycodes  { include "evdev" };
    xkb_types     { include "complete" };
    xkb_compat    { include "complete" };
    xkb_symbols   { include "custom(ctrl)" };
};
'
# xkb_symbols   { include "us+custom(ctrl)" };
# xkb_geometry  { include "pc(pc104)" };
